GET http://localhost:3000/category/getAll HTTP/1.1

###

GET http://localhost:3000/category/getById/1 HTTP/1.1

###

POST http://localhost:3000/category/create HTTP/1.1
Content-Type: application/json

{
  "title": "Хлебобулочные изделия"
}