GET http://localhost:3000/products

###

GET http://localhost:3000/category

###

GET http://localhost:3000/products/2

###

GET http://localhost:3000/products/qweqwe
###

POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "milk",
  "price": 50
}